INSERT INTO workspace_cfop (id, code, description, type, active)
VALUES
    (uuid_generate_v4(), '1101', 'Compra para industrialização ou produção rural', 'entrada', TRUE),
    (uuid_generate_v4(), '1102', 'Compra para comercialização', 'entrada', TRUE),
    (uuid_generate_v4(), '1111', 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial', 'entrada', TRUE),
    (uuid_generate_v4(), '1113', 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil', 'entrada', TRUE),
    (uuid_generate_v4(), '1116', 'Compra para industrialização ou produção rural originada de encomenda para recebimento futuro', 'entrada', TRUE),
    (uuid_generate_v4(), '1117', 'Compra para comercialização originada de encomenda para recebimento futuro', 'entrada', TRUE),
    (uuid_generate_v4(), '1120', 'Compra para industrialização, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1121', 'Compra para comercialização, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1122', 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1124', 'Industrialização efetuada por outra empresa', 'entrada', TRUE),
    (uuid_generate_v4(), '1126', 'Compra para utilização na prestação de serviço sujeita ao ICMS', 'entrada', TRUE),
    (uuid_generate_v4(), '1151', 'Transferência para industrialização ou produção rural', 'entrada', TRUE),
    (uuid_generate_v4(), '1152', 'Transferência para comercialização', 'entrada', TRUE),
    (uuid_generate_v4(), '1153', 'Transferência de energia elétrica para distribuição', 'entrada', TRUE),
    (uuid_generate_v4(), '1154', 'Transferência para utilização na prestação de serviço', 'entrada', TRUE),
    (uuid_generate_v4(), '1155', 'Transferência de bem do ativo imobilizado', 'entrada', TRUE),
    (uuid_generate_v4(), '1156', 'Transferência de material de uso ou consumo', 'entrada', TRUE),
    (uuid_generate_v4(), '1157', 'Transferência de mercadoria recebida anteriormente em consignação mercantil', 'entrada', TRUE),
    (uuid_generate_v4(), '1158', 'Transferência de mercadoria recebida anteriormente em consignação industrial', 'entrada', TRUE),
    (uuid_generate_v4(), '1159', 'Transferência de mercadoria recebida anteriormente em consignação mercantil, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1201', 'Devolução de venda de produção do estabelecimento', 'entrada', TRUE),
    (uuid_generate_v4(), '1202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', 'entrada', TRUE),
    (uuid_generate_v4(), '1203', 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 'entrada', TRUE),
    (uuid_generate_v4(), '1204', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 'entrada', TRUE),
    (uuid_generate_v4(), '1205', 'Anulação de valor relativo à prestação de serviço de comunicação', 'entrada', TRUE),
    (uuid_generate_v4(), '1206', 'Anulação de valor relativo à prestação de serviço de transporte', 'entrada', TRUE),
    (uuid_generate_v4(), '1207', 'Anulação de valor relativo à venda de energia elétrica', 'entrada', TRUE),
    (uuid_generate_v4(), '1208', 'Devolução de produção do estabelecimento, remetida em transferência', 'entrada', TRUE),
    (uuid_generate_v4(), '1209', 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência', 'entrada', TRUE),
    (uuid_generate_v4(), '1251', 'Compra de energia elétrica para distribuição ou comercialização', 'entrada', TRUE),
    (uuid_generate_v4(), '1252', 'Compra de energia elétrica por estabelecimento industrial', 'entrada', TRUE),
    (uuid_generate_v4(), '1253', 'Compra de energia elétrica por estabelecimento comercial', 'entrada', TRUE),
    (uuid_generate_v4(), '1254', 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte', 'entrada', TRUE),
    (uuid_generate_v4(), '1255', 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação', 'entrada', TRUE),
    (uuid_generate_v4(), '1256', 'Compra de energia elétrica por estabelecimento de produtor rural', 'entrada', TRUE),
    (uuid_generate_v4(), '1257', 'Compra de energia elétrica para consumo por demanda contratada', 'entrada', TRUE),
    (uuid_generate_v4(), '1301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', 'entrada', TRUE),
    (uuid_generate_v4(), '1302', 'Aquisição de serviço de comunicação por estabelecimento industrial', 'entrada', TRUE),
    (uuid_generate_v4(), '1303', 'Aquisição de serviço de comunicação por estabelecimento comercial', 'entrada', TRUE),
    (uuid_generate_v4(), '1304', 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte', 'entrada', TRUE),
    (uuid_generate_v4(), '1305', 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de comunicação', 'entrada', TRUE),
    (uuid_generate_v4(), '1306', 'Aquisição de serviço de comunicação por estabelecimento de produtor rural', 'entrada', TRUE),
    (uuid_generate_v4(), '1351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', 'entrada', TRUE),
    (uuid_generate_v4(), '1352', 'Aquisição de serviço de transporte por estabelecimento industrial', 'entrada', TRUE),
    (uuid_generate_v4(), '1353', 'Aquisição de serviço de transporte por estabelecimento comercial', 'entrada', TRUE),
    (uuid_generate_v4(), '1354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de transporte', 'entrada', TRUE),
    (uuid_generate_v4(), '1355', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', 'entrada', TRUE),
    (uuid_generate_v4(), '1356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural', 'entrada', TRUE),
    (uuid_generate_v4(), '1360', 'Recebimento, por transferência, de crédito de ICMS', 'entrada', TRUE),
    (uuid_generate_v4(), '1361', 'Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo credor de ICMS', 'entrada', TRUE),
    (uuid_generate_v4(), '1401', 'Compra para industrialização ou produção rural de mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1403', 'Compra para comercialização de mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1406', 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1407', 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1408', 'Transferência para industrialização ou produção rural de mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1409', 'Transferência para comercialização de mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1410', 'Devolução de venda de produção do estabelecimento, quando a mercadoria estiver sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1411', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, quando a mercadoria estiver sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1414', 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento, quando a mercadoria estiver sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1415', 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento, quando a mercadoria estiver sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1501', 'Entrada de mercadoria recebida com fim específico de exportação', 'entrada', TRUE),
    (uuid_generate_v4(), '1503', 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento', 'entrada', TRUE),
    (uuid_generate_v4(), '1504', 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de mercadoria adquirida ou recebida de terceiros', 'entrada', TRUE),
    (uuid_generate_v4(), '1505', 'Entrada de mercadoria recebida com fim específico de exportação de mercadoria industrializada por encomenda', 'entrada', TRUE),
    (uuid_generate_v4(), '1506', 'Entrada de mercadoria recebida com fim específico de exportação de mercadoria industrializada por encomenda, de mercadoria adquirida ou recebida de terceiros', 'entrada', TRUE),
    (uuid_generate_v4(), '1551', 'Compra de bem para o ativo imobilizado', 'entrada', TRUE),
    (uuid_generate_v4(), '1552', 'Transferência de bem do ativo imobilizado', 'entrada', TRUE),
    (uuid_generate_v4(), '1553', 'Devolução de venda de bem do ativo imobilizado', 'entrada', TRUE),
    (uuid_generate_v4(), '1554', 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento', 'entrada', TRUE),
    (uuid_generate_v4(), '1555', 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento', 'entrada', TRUE),
    (uuid_generate_v4(), '1556', 'Compra de material para uso ou consumo', 'entrada', TRUE),
    (uuid_generate_v4(), '1557', 'Transferência de material para uso ou consumo', 'entrada', TRUE),
    (uuid_generate_v4(), '1558', 'Devolução de venda de material de uso ou consumo', 'entrada', TRUE),
    (uuid_generate_v4(), '1601', 'Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa', 'entrada', TRUE),
    (uuid_generate_v4(), '1602', 'Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento da mesma empresa', 'entrada', TRUE),
    (uuid_generate_v4(), '1603', 'Ressarcimento de ICMS retido por substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1604', 'Lançamento do crédito relativo à compra de bem para o ativo imobilizado', 'entrada', TRUE),
    (uuid_generate_v4(), '1605', 'Recebimento, por transferência, de crédito de ICMS de mercadoria recebida para industrialização e devolvida ao estabelecimento remetente', 'entrada', TRUE),
    (uuid_generate_v4(), '1606', 'Recebimento, por transferência, de crédito de ICMS de mercadoria recebida para industrialização e devolvida ao estabelecimento remetente, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1651', 'Compra de combustível ou lubrificante para industrialização subsequente', 'entrada', TRUE),
    (uuid_generate_v4(), '1652', 'Compra de combustível ou lubrificante para comercialização', 'entrada', TRUE),
    (uuid_generate_v4(), '1653', 'Compra de combustível ou lubrificante por consumidor ou usuário final', 'entrada', TRUE),
    (uuid_generate_v4(), '1654', 'Transferência de combustível ou lubrificante para industrialização subsequente', 'entrada', TRUE),
    (uuid_generate_v4(), '1655', 'Transferência de combustível ou lubrificante para comercialização', 'entrada', TRUE),
    (uuid_generate_v4(), '1656', 'Transferência de combustível ou lubrificante para utilização na prestação de serviço', 'entrada', TRUE),
    (uuid_generate_v4(), '1657', 'Transferência de combustível ou lubrificante para utilização na prestação de serviço de transporte', 'entrada', TRUE),
    (uuid_generate_v4(), '1658', 'Transferência de combustível ou lubrificante para utilização na prestação de serviço de comunicação', 'entrada', TRUE),
    (uuid_generate_v4(), '1659', 'Transferência de combustível ou lubrificante para utilização na prestação de serviço de comunicação, de transporte ou de industrialização subsequente', 'entrada', TRUE),
    (uuid_generate_v4(), '1660', 'Transferência de combustível ou lubrificante para utilização na prestação de serviço de comunicação, de transporte ou de industrialização subsequente, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1901', 'Entrada para industrialização por encomenda', 'entrada', TRUE),
    (uuid_generate_v4(), '1902', 'Retorno de mercadoria remetida para industrialização por encomenda', 'entrada', TRUE),
    (uuid_generate_v4(), '1903', 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo', 'entrada', TRUE),
    (uuid_generate_v4(), '1904', 'Retorno de remessa para venda fora do estabelecimento', 'entrada', TRUE),
    (uuid_generate_v4(), '1905', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral', 'entrada', TRUE),
    (uuid_generate_v4(), '1906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', 'entrada', TRUE),
    (uuid_generate_v4(), '1907', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral', 'entrada', TRUE),
    (uuid_generate_v4(), '1908', 'Entrada de bem por conta e ordem de terceiros, remetido para depósito fechado ou armazém geral', 'entrada', TRUE),
    (uuid_generate_v4(), '1909', 'Retorno de bem remetido por conta e ordem de terceiros, para depósito fechado ou armazém geral', 'entrada', TRUE),
    (uuid_generate_v4(), '1910', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1911', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1912', 'Retorno simbólico de mercadoria remetida para depósito fechado', 'entrada', TRUE);
    
INSERT INTO public.cfop (id, codigo, descricao, tipo, ativo) VALUES
    (uuid_generate_v4(), '1913', 'Entrada de bem por conta e ordem de terceiros, remetido para depósito fechado ou armazém geral, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1914', 'Retorno de bem remetido por conta e ordem de terceiros, para depósito fechado ou armazém geral, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1915', 'Entrada de mercadoria recebida para industrialização por encomenda, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1916', 'Retorno de mercadoria remetida para industrialização por encomenda, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1917', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral, de mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1918', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral, de mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1919', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral, de mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1920', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral, de mercadoria sujeita ao regime de substituição tributária, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1921', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral, de mercadoria sujeita ao regime de substituição tributária, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE),
    (uuid_generate_v4(), '1922', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral, de mercadoria sujeita ao regime de substituição tributária, em operação com mercadoria sujeita ao regime de substituição tributária', 'entrada', TRUE);
    